version: '3.8'
volumes:
  main_db_vol:
    driver: local
  cache:
    driver: local

networks:
  backend-to-cache:
    driver: bridge
  backend-to-main_db:
    driver: bridge

services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - '3000:${PORT}'
    volumes:
      - ./src:/workspace/src
      - ./public:/workspace/public
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      # if you change this, change the MYSQL_DATABASE in the main_db service
      - DATABASE_NAME=${M_DATABASE_NAME}
      - M_DATABASE_PORT=${M_DATABASE_PORT}
      - M_DATABASE_USER=${M_DATABASE_USER}
      - M_DATABASE_PASSWORD=${M_DATABASE_PASSWORD}
      - M_DATABASE_HOST=${M_DATABASE_HOST}
      - M_DATABASE_NAME=${M_DATABASE_NAME}
      - REDIS_URL=${REDIS_URL}
      - M_DATABASE_TIME_TO_CHECK=${M_DATABASE_TIME_TO_CHECK}
    networks:
      - backend-to-cache
      - backend-to-main_db
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

