version: '3.8'

services:
  backend:
    container_name: portfolio-rodrigo
    build:
      context: .
    ports:
      - '8010:${PORT}'
    volumes:
      - ./src:/workspace/src
      - ./public:/workspace/public
    environment:
      - NODE_ENV=development
      # if you change this, change the MYSQL_DATABASE in the main_db service
      - PORT=${PORT}
      # if you change this, change the MYSQL_DATABASE in the main_db service
      - DATABASE_NAME=${M_DATABASE_NAME}
      - M_DATABASE_PORT=${M_DATABASE_PORT}
      - M_DATABASE_USER=${M_DATABASE_USER}
      - M_DATABASE_PASSWORD=${M_DATABASE_PASSWORD}
      - M_DATABASE_HOST=${M_DATABASE_HOST}
      - M_DATABASE_NAME=${M_DATABASE_NAME}
      - REDIS_URL=${REDIS_URL}
      - M_DATABASE_TIME_TO_CHECK=${M_DATABASE_TIME_TO_CHECK}

